 name: CI
 
 on:
   workflow_dispatch:
   push:
    branches:
      - main
 
 jobs:
   build-non-mac:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.GHPAT }}
         repository: "rdp-studio/xfc-private"

     - name: Build
       run: |
         docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller -F --clean -y --dist ./dist/windows/ --workpath /tmp wallet.py'
         zip -r $GITHUB_WORKSPACE/wallet-win.zip $GITHUB_WORKSPACE/dist/windows/wallet.exe
         docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-linux:latest 'pyinstaller -F --clean -y --dist ./dist/linux/ --workpath /tmp wallet.py'
         zip -r $GITHUB_WORKSPACE/wallet-linux.zip $GITHUB_WORKSPACE/dist/linux/wallet

     - uses: actions/upload-artifact@v2
       with:
          name: Windows
          path: ${{ github.workspace }}/wallet-win.zip

     - uses: actions/upload-artifact@v2
       with:
          name: Linux
          path: ${{ github.workspace }}/wallet-linux.zip

   build-mac:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.GHPAT }}
         repository: "rdp-studio/xfc-private"

     - uses: actions/setup-python@v4 
       with:
         python-version: '3.7' 

     - name: Build
       run: |
         pip install pyinstaller requests
         pyinstaller -F --clean -y --dist ./dist/macos/ --workpath /tmp wallet.py
         zip -r $GITHUB_WORKSPACE/wallet-macos.zip $GITHUB_WORKSPACE/dist/macos/wallet

     - uses: actions/upload-artifact@v2
       with:
          name: MacOS
          path: ${{ github.workspace }}/wallet-macos.zip
